name: artefacto

on:
  push: 
    branches: master

jobs:
  first-job:
    name: "Primer Hola"
    env: 
      michi: version1
    runs-on: ubuntu-latest
    outputs: 
      salida: ${{ steps.step_02.outputs.michiTest }}
    steps: 
      - name: Working dir
        run : |
          echo "Archivo prueba, hola" >> test.log
      - name: Subir artefactp
        uses: actions/upload-artifact@v4
        with:
          name: archivotest
          path: test.log
    