name: artefacto

on:
  push: 
    branches: master

jobs:
  first-job:
    name: "Crear Artefacto"
    env: 
      michi: version1
    runs-on: ubuntu-latest
    outputs: 
      salida: ${{ steps.step_02.outputs.michiTest }}
    steps: 
      - name: Working dir
        run : |
          echo "Archivo prueba, hola" >> test.log
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivotest
          path: test.log
  second-job:
    name: "Descargar Artefacto"
    runs-on: ubuntu-latest
    steps:
      - name: descargarTest
        uses: actions/download-artifact@
        with:
          name: archivotest
      - name: verarchivo
        run: cat test.log