name: deploy a prod

on:
  push: 
    branches: master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: HOLA MUNDO
        run: echo "Hola Mundo"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: HOLA MUNDO DOS
        run: echo "HolaMundo2" 
      - name: listar 
        run: ls -ltr
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: HOLA MUNDO tres
        run: echo "HolaMundo3" 
      - name: generar carpeta  
        run: ls -ltr
