name: deploy a prod

on:
  push: 
    branches: master

jobs:
  first-job:
    name: "Primer Hola"
    runs-on: ubuntu-latest
    steps: 
      - name: Working dir
        run: ls -al
      - name: action
        uses: actions/checkout@v4
      - name: Working dir after
        run: ls -al
  second-job:
    name: "Segundo Hola"
    env:
      test: michi
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: HOLA MUNDO DOS
        run: echo "HolaMundo2 $test" 
      - name: listar 
        run: ls -ltr
  third-job:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: HOLA MUNDO tres
        run: echo "HolaMundo3" 
      - name: generar carpeta  
        run: echo "Hola ${{ github.actor }}"
