name: deploy a prod

on:
  push: 
    branches: master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: HOLA MUNDO
        run: echo "Hola Mundo"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: HOLA MUNDO DOS
        run: echo "HolaMundo2"  |
            ls
