
name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurara Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '18'