name: deploy a prod

on:
  push: 
    branches: master

jobs:
  first-job:
    name: "Primer Hola"
    env: 
      michi: version1
    runs-on: ubuntu-latest
    steps: 
      - name: Working dir
        run: echo "$GITHUB_OUTPUT"
      - name: PASAMOS VAR TEST
        run: echo " $michi" >> $GITHUB_OUTPUT
  second-job:
    name: "Segundo Hola"
    env:
      test: michi
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Revisamos VAR TEST
        run: echo "$GITHUB_OUTPUT"
  second-job:
