name: deploy a prod

on:
  push: 
    branches: main

jobs:
  first-job:
    name: "Primer Hola"
    env: 
      michi: version1
    runs-on: ubuntu-latest
    outputs: 
      salida: ${{ steps.step_02.outputs.michiTest }}
    steps: 
      - name: Working dir
        id: step_01
        run: echo "$GITHUB_OUTPUT"

      - name: PASAMOS VAR TEST
        id: step_02
        run: echo "michiTest=version" >> $GITHUB_OUTPUT
      - name: Imprimo Var
        run: echo "michiTest"

      - name: Recibimos VAR TEST
        run: echo "${{ steps.step_02.outputs.michiTest }}"
  second-job:
    name: "Segundo Hola"
    needs: first-job
    runs-on: ubuntu-latest
    env:
      SALIDA: ${{ needs.first-job.outputs.salida }}
    steps:
      - name: Revisamos VAR TEST
        run: echo "$SALIDA 5.5"