name: deploy a prod

on:
  push: 
    branches: master

jobs:
  first-job:
    name: "Primer Hola"
    env: 
      michi: version1
    runs-on: ubuntu-latest
    steps: 
      - name: Working dir
        id: step_01
        run: echo "$GITHUB_OUTPUT"
      - name: PASAMOS VAR TEST
        run: echo " var michiTest=version" >> $GITHUB_OUTPUT
      - name: Recibimos VAR TEST
        run: echo "${{ steps.step_01.outputs.michiTest }}"
  second-job:
    name: "Segundo Hola"
    env:
      test: michi
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Revisamos VAR TEST
        run: echo "Hola"